#!/bin/bash
set -euo pipefail

usage() {
	cat <<'EOF'
Usage: debian/scripts/update-config.sh /path/to/linux

Regenerate debian/config/cv181x-sodoport.config from:
1. debian/config/base/milkv-duo_defconfig
2. debian/config/fragments/debian-common.fragment
3. debian/config/fragments/initramfs.fragment
4. debian/config/fragments/sg2002-soc.fragment
5. debian/config/fragments/cv181x-sodoport.fragment

The kernel tree must be a full source checkout and must contain
scripts/kconfig/merge_config.sh.
EOF
}

if [ "${1:-}" = "-h" ] || [ "${1:-}" = "--help" ]; then
	usage
	exit 0
fi

if [ $# -ne 1 ]; then
	usage >&2
	exit 1
fi

repo_dir=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
linux_dir=$(CDPATH= cd -- "$1" && pwd)
config_dir="$repo_dir/config"
out_dir=$(mktemp -d)
trap 'rm -rf "$out_dir"' EXIT

base_config="$config_dir/base/milkv-duo_defconfig"
merge_script="$linux_dir/scripts/kconfig/merge_config.sh"
generated_config="$config_dir/cv181x-sodoport.config"

fragments=(
	"$config_dir/fragments/debian-common.fragment"
	"$config_dir/fragments/initramfs.fragment"
	"$config_dir/fragments/sg2002-soc.fragment"
	"$config_dir/fragments/cv181x-sodoport.fragment"
)

for path in "$linux_dir/Makefile" "$merge_script" "$base_config"; do
	if [ ! -e "$path" ]; then
		echo "Missing required path: $path" >&2
		exit 1
	fi
done

for path in "$linux_dir/scripts/basic/Makefile" "$linux_dir/init/Kconfig" "$linux_dir/fs/Kconfig"; do
	if [ ! -e "$path" ]; then
		echo "Kernel tree looks incomplete for olddefconfig: $path is missing" >&2
		echo "Use a full upstream checkout instead of a sparse subset." >&2
		exit 1
	fi
done

for fragment in "${fragments[@]}"; do
	if [ ! -f "$fragment" ]; then
		echo "Missing fragment: $fragment" >&2
		exit 1
	fi
done

ARCH=riscv "$merge_script" -m -O "$out_dir" "$base_config" "${fragments[@]}"

make -C "$linux_dir" O="$out_dir" ARCH=riscv olddefconfig

{
		printf '%s\n' \
			"# Generated by debian/scripts/update-config.sh." \
			"# Replace debian-common.fragment with a Debian-derived intersection fragment when available."
		cat "$out_dir/.config"
} > "$generated_config"

echo "Updated $generated_config"
